[build]
  publish = "dist"
  command = "npm run build"

# [context.production]
#   publish = "dist"
#   command = "npm run build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-transform"
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true